Repository goalapa/spring-cacamuca, pull requests merged in 2023-07, with the labels that each got.

#25 Feature/report create (#15) 신고 저장
  src/main/java/com/goalapa/cacamuca/reportDomain/command/application/controller/Controller.java
  src/main/java/com/goalapa/cacamuca/reportDomain/command/application/controller/ReportController.java
  src/main/java/com/goalapa/cacamuca/reportDomain/command/application/dto/Dto.java
  src/main/java/com/goalapa/cacamuca/reportDomain/command/application/dto/ReportDTO.java
  src/main/java/com/goalapa/cacamuca/reportDomain/command/application/service/ReportServiceImpl.java
  src/main/java/com/goalapa/cacamuca/reportDomain/command/application/service/Service.java
  src/main/java/com/goalapa/cacamuca/reportDomain/command/domain/aggregate/entity/Report.java
  src/main/java/com/goalapa/cacamuca/reportDomain/command/domain/aggregate/vo/ReportTypeVO.java
  src/main/java/com/goalapa/cacamuca/reportDomain/command/domain/repository/ReportRepository.java
  src/main/java/com/goalapa/cacamuca/reportDomain/command/domain/service/ReportCheckNullService.java
  src/main/java/com/goalapa/cacamuca/reportDomain/command/domain/service/ReportService.java
  src/main/java/com/goalapa/cacamuca/reportDomain/command/infrastructure/service/ReportCheckNullServiceImpl.java
  src/main/java/com/goalapa/cacamuca/reportDomain/command/ininfrastructure/repository/Repository.java
  src/main/java/com/goalapa/cacamuca/reportDomain/command/ininfrastructure/service/Service.java
  src/main/java/com/goalapa/cacamuca/reportDomain/query/domain/repository/ReportMybatisRepository.java
  src/main/java/com/goalapa/cacamuca/reportDomain/query/infrastructure/repository/ReportMybatisRepositoryImpl.java
  src/main/resources/static/index.html
  src/main/resources/templates/report.html
Labels: ✨feature

#34 Feature/request(#33) 전달받은 request 저장
  src/main/java/com/goalapa/cacamuca/blackListDomain/command/infrasturcture/repository/Repository.java
  src/main/java/com/goalapa/cacamuca/blackListDomain/command/infrasturcture/service/Service.java
  src/main/java/com/goalapa/cacamuca/blackListDomain/command/ininfrastructure/repository/Repository.java
  src/main/java/com/goalapa/cacamuca/blackListDomain/command/ininfrastructure/service/Service.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/application/controller/Controller.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/application/controller/RequestController.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/application/dto/Dto.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/application/dto/RequestDTO.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/application/service/SaveRequestServiceImpl.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/application/service/Service.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/domain/aggregate/entity/Request.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/domain/repository/RequestRepository.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/domain/service/CheckRequestService.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/domain/service/SaveRequestService.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/domain/service/Service.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/infrastructure/service/CheckRequestServiceImpl.java
  src/main/resources/db/data/data.sql
  src/main/resources/static/index.html
  src/main/resources/templates/request.html
Labels: ✨feature

#54 Feature/request (#38, #52) entity,vo 수정/요청 게시글 작성 페이지 프론
  src/main/java/com/goalapa/cacamuca/categoryDomain/command/domain/aggregate/entity/Category.java
  src/main/java/com/goalapa/cacamuca/categoryDomain/command/ininfrastructure/repository/Repository.java
  src/main/java/com/goalapa/cacamuca/categoryDomain/command/ininfrastructure/service/Service.java
  src/main/java/com/goalapa/cacamuca/memberDomain/query/application/service/AuthenticationService.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/application/controller/RequestController.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/application/dto/RequestDTO.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/application/dto/RequestPicDTO.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/application/service/SaveRequestPicServiceImpl.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/application/service/SaveRequestServiceImpl.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/domain/aggregate/entity/Request.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/domain/aggregate/entity/RequestPic.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/domain/aggregate/vo/RequestCategoryVO.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/domain/aggregate/vo/RequestCountry.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/domain/aggregate/vo/RequestFoodType.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/domain/aggregate/vo/RequestMemberNo.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/domain/aggregate/vo/RequestMemberVO.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/domain/repository/RequestPicRepository.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/domain/service/CheckRequestPicService.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/domain/service/SaveRequestPicService.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/infrastructure/service/CheckRequestPicServiceImpl.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/infrastructure/service/CheckRequestServiceImpl.java
  src/main/resources/db/data/data.sql
  src/main/resources/image/d2c67612db8d4fc793bff0699c635a7f.jpg
  src/main/resources/templates/request.html
Labels: ✨feature, 🎨design

#79 Feature : (#78) 신고 리스트 피드백 반영
  src/main/java/com/goalapa/cacamuca/reportDomain/query/application/service/ReportPageServiceImpl.java
  src/main/resources/templates/report-page.html
Labels: ✨feature, ✅fix

#76 Feature : (#71) 에러페이지 추가
  src/main/resources/templates/error/400.html
  src/main/resources/templates/error/403.html
  src/main/resources/templates/error/404.html
  src/main/resources/templates/error/500.html
Labels: ✨feature, 🎨design

#101 Feature/review (#18) 좋아요 이슈 해결
  build.gradle
  src/main/java/com/goalapa/cacamuca/likeDomain/command/domain/aggregate/entity/Like.java
  src/main/java/com/goalapa/cacamuca/likeDomain/command/domain/aggregate/entity/LikeId.java
  src/main/java/com/goalapa/cacamuca/likeDomain/command/domain/repository/LikeRepository.java
  src/main/java/com/goalapa/cacamuca/memberDomain/command/application/controller/CommandMemberController.java
  src/main/java/com/goalapa/cacamuca/memberDomain/query/application/controller/QueryMemberController.java
  src/main/java/com/goalapa/cacamuca/requestDomain/query/application/controller/FindRequestController.java
  src/main/java/com/goalapa/cacamuca/reviewDomain/command/application/controller/ReviewController.java
  src/main/java/com/goalapa/cacamuca/reviewDomain/command/application/service/ReviewService.java
  src/main/java/com/goalapa/cacamuca/reviewDomain/command/domain/aggregate/entity/Review.java
  src/main/java/com/goalapa/cacamuca/reviewDomain/command/domain/aggregate/vo/ReviewWriter.java
  src/main/java/com/goalapa/cacamuca/reviewDomain/command/domain/repository/ReviewRepository.java
  src/main/java/com/goalapa/cacamuca/reviewDomain/command/infrastructure/service/ReviewValidationService.java
  src/main/java/com/goalapa/cacamuca/reviewDomain/query/application/controller/SelectReviewController.java
  src/main/resources/db/data/data.sql
  src/main/resources/templates/common/header.html
  src/main/resources/templates/member/login.html
  src/main/resources/templates/member/registration.html
  src/main/resources/templates/review.html
  src/main/resources/templates/reviewDetail.html
  src/main/resources/templates/selectReviews.html
Labels: 🐞bugfix

#102 Feature/request [요청], [식품] (#80, #85, #96, #98)
  src/main/java/com/goalapa/cacamuca/foodDomain/command/application/controller/Controller.java
  src/main/java/com/goalapa/cacamuca/foodDomain/command/application/controller/FoodController.java
  src/main/java/com/goalapa/cacamuca/foodDomain/command/application/dto/Dto.java
  src/main/java/com/goalapa/cacamuca/foodDomain/command/application/dto/FoodDTO.java
  src/main/java/com/goalapa/cacamuca/foodDomain/command/application/dto/FoodPicDTO.java
  src/main/java/com/goalapa/cacamuca/foodDomain/command/application/service/SaveFoodFromRequestImpl.java
  src/main/java/com/goalapa/cacamuca/foodDomain/command/application/service/Service.java
  src/main/java/com/goalapa/cacamuca/foodDomain/command/domain/aggregate/entity/Food.java
  src/main/java/com/goalapa/cacamuca/foodDomain/command/domain/aggregate/entity/FoodPic.java
  src/main/java/com/goalapa/cacamuca/foodDomain/command/domain/aggregate/vo/Country.java
  src/main/java/com/goalapa/cacamuca/foodDomain/command/domain/aggregate/vo/FoodCategoryVO.java
  src/main/java/com/goalapa/cacamuca/foodDomain/command/domain/aggregate/vo/FoodType.java
  src/main/java/com/goalapa/cacamuca/foodDomain/command/domain/service/SaveFoodFromRequest.java
  src/main/java/com/goalapa/cacamuca/foodDomain/command/domain/service/Service.java
  src/main/java/com/goalapa/cacamuca/foodDomain/command/ininfrastructure/repository/Repository.java
  src/main/java/com/goalapa/cacamuca/foodDomain/command/ininfrastructure/service/Service.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/application/controller/RequestController.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/application/service/DeleteRequestImpl.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/application/service/DeleteRequestPicImpl.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/application/service/SaveRequestImpl.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/application/service/SaveRequestPicImpl.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/application/service/SaveRequestToFoodImpl.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/domain/repository/RequestRepository.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/domain/service/CheckRequest.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/domain/service/CheckRequestPic.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/domain/service/DeleteRequest.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/domain/service/DeleteRequestPic.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/domain/service/SaveRequest.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/domain/service/SaveRequestPic.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/domain/service/SaveRequestToFood.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/infrastructure/service/CheckRequestPicServiceImpl.java
  src/main/java/com/goalapa/cacamuca/requestDomain/command/infrastructure/service/CheckRequestServiceImpl.java
  src/main/java/com/goalapa/cacamuca/requestDomain/query/application/controller/FindRequestController.java
  src/main/resources/db/data/data.sql
  src/main/resources/templates/request-detail.html
  src/main/resources/templates/request-list.html
  src/main/resources/templates/request.html
Labels: ✨feature, 🛠️refactor, ✅fix

#94 Feature/report : (#95) 블랙리스트 도메인 삭제/수정, 신고 페이지 디자인 수정
  src/main/java/com/goalapa/cacamuca/blackListDomain/command/application/controller/Controller.java
  src/main/java/com/goalapa/cacamuca/blackListDomain/command/application/dto/Dto.java
  src/main/java/com/goalapa/cacamuca/blackListDomain/command/application/service/Service.java
  src/main/java/com/goalapa/cacamuca/blackListDomain/command/domain/service/Service.java
  src/main/java/com/goalapa/cacamuca/blackListDomain/command/infrasturcture/repository/Repository.java
  src/main/java/com/goalapa/cacamuca/blackListDomain/command/infrasturcture/service/Service.java
  src/main/java/com/goalapa/cacamuca/blackListDomain/query/application/controller/Controller.java
  src/main/java/com/goalapa/cacamuca/blackListDomain/query/application/dto/Dto.java
  src/main/java/com/goalapa/cacamuca/blackListDomain/query/application/service/Service.java
  src/main/java/com/goalapa/cacamuca/blackListDomain/query/domain/entity/Entity.java
  src/main/java/com/goalapa/cacamuca/blackListDomain/query/domain/service/Service.java
  src/main/java/com/goalapa/cacamuca/blackListDomain/query/infrastructure/repository/Repository.java
  src/main/java/com/goalapa/cacamuca/blackListDomain/query/infrastructure/service/Service.java
  src/main/java/com/goalapa/cacamuca/reportDomain/command/application/controller/ReportController.java
  src/main/java/com/goalapa/cacamuca/reportDomain/command/application/dto/ReportDeleteDTO.java
  src/main/java/com/goalapa/cacamuca/reportDomain/command/application/service/ReportServiceImpl.java
  src/main/java/com/goalapa/cacamuca/reportDomain/command/domain/aggregate/entity/BlackList.java
  src/main/java/com/goalapa/cacamuca/reportDomain/command/domain/repository/BlackListRepository.java
  src/main/java/com/goalapa/cacamuca/reportDomain/command/domain/service/ReportService.java
  src/main/java/com/goalapa/cacamuca/reportDomain/query/application/controller/ReportQueryController.java
  src/main/resources/mapper/ReportMapper.xml
  src/main/resources/templates/reportAdminPage.html
Labels: ✏️rename, 🎨design

#100 Feature/member (#95, #99) 회원가입 기능 이슈 디버깅(배포 피드백), 회원목록조회
  src/main/java/com/goalapa/cacamuca/memberDomain/command/application/controller/CommandMemberController.java
  src/main/java/com/goalapa/cacamuca/memberDomain/command/application/service/MemberServiceImpl.java
  src/main/java/com/goalapa/cacamuca/memberDomain/query/application/controller/QueryMemberController.java
  src/main/java/com/goalapa/cacamuca/memberDomain/query/application/service/AuthenticationService.java
  src/main/java/com/goalapa/cacamuca/memberDomain/query/application/service/QueryMemberServiceImpl.java
  src/main/java/com/goalapa/cacamuca/memberDomain/query/domain/aggregate/entity/Member.java
  src/main/java/com/goalapa/cacamuca/memberDomain/query/domain/repository/MemberMapper.java
  src/main/resources/mapper/MemberMapper.xml
  src/main/resources/static/js/registration.js
  src/main/resources/templates/adminList.html
  src/main/resources/templates/common/adminAside.html
  src/main/resources/templates/common/adminHeader.html
  src/main/resources/templates/common/aside.html
  src/main/resources/templates/common/header.html
  src/main/resources/templates/member/registration.html
Labels: 🐞bugfix, ✨feature

#106 Feature/food (#48) 식품 Entity, VO 추가 및 수정
  src/main/java/com/goalapa/cacamuca/foodDomain/command/application/dto/FoodDTO.java
  src/main/java/com/goalapa/cacamuca/foodDomain/command/application/service/SaveFoodFromRequestImpl.java
  src/main/java/com/goalapa/cacamuca/foodDomain/command/domain/aggregate/entity/Food.java
  src/main/java/com/goalapa/cacamuca/foodDomain/command/domain/aggregate/vo/CountryVO.java
  src/main/java/com/goalapa/cacamuca/foodDomain/command/domain/aggregate/vo/FoodTypeVO.java
Labels: ✨feature

#123 Fix/member (#99) [회원] 회원목록조회
  src/main/java/com/goalapa/cacamuca/memberDomain/query/application/controller/QueryMemberController.java
  src/main/java/com/goalapa/cacamuca/memberDomain/query/application/service/QueryMemberServiceImpl.java
  src/main/java/com/goalapa/cacamuca/memberDomain/query/domain/aggregate/dto/MemberDTO.java
  src/main/java/com/goalapa/cacamuca/memberDomain/query/domain/repository/MemberMapper.java
  src/main/resources/db/data/data.sql
  src/main/resources/mapper/MemberMapper.xml
  src/main/resources/templates/adminList.html
Labels: ✨feature, ✅fix

#129 #105 카테고리 db 수정
  src/main/java/com/goalapa/cacamuca/categoryDomain/command/application/controller/CategoryController.java
  src/main/java/com/goalapa/cacamuca/categoryDomain/command/application/service/AddCategoryService.java
  src/main/java/com/goalapa/cacamuca/categoryDomain/command/application/service/UpdateCategoryService.java
  src/main/java/com/goalapa/cacamuca/categoryDomain/command/domain/aggregate/entity/CategoryEntity.java
  src/main/java/com/goalapa/cacamuca/categoryDomain/command/domain/repository/CategoryRepository.java
  src/main/resources/templates/category/add-result.html
  src/main/resources/templates/category/add.html
  src/main/resources/templates/category/update-category.html
  src/main/resources/templates/category/update-result.html
  src/main/resources/templates/category/update.html
  src/main/resources/templates/food-regist.html
Labels: ✏️rename

#138 Feature/review (#137) [리뷰] 검색 및 목록 프론트
  src/main/java/com/goalapa/cacamuca/foodDomain/command/domain/repository/FoodRepository.java
  src/main/java/com/goalapa/cacamuca/reviewDomain/command/application/controller/ReviewController.java
  src/main/java/com/goalapa/cacamuca/reviewDomain/query/application/controller/SelectReviewController.java
  src/main/java/com/goalapa/cacamuca/reviewDomain/query/application/dto/QueryReviewFoodDTO.java
  src/main/java/com/goalapa/cacamuca/reviewDomain/query/application/dto/QueryReviewWriterDTO.java
  src/main/java/com/goalapa/cacamuca/reviewDomain/query/application/service/SelectReviewService.java
  src/main/java/com/goalapa/cacamuca/reviewDomain/query/domain/repository/ReviewMapper.java
  src/main/resources/db/data/data.sql
  src/main/resources/mapper/ReviewMapper.xml
  src/main/resources/templates/review.html
  src/main/resources/templates/review/report.html
  src/main/resources/templates/review/reviewDetail.html
  src/main/resources/templates/review/search.html
  src/main/resources/templates/review/selectReviews.html
Labels: ✨feature, ✅fix

#149 feat : (#83) [공통] 메인페이지
  src/main/java/com/goalapa/cacamuca/foodDomain/query/application/controller/MainController.java
  src/main/java/com/goalapa/cacamuca/foodDomain/query/domain/mapper/FoodMapper.java
  src/main/java/com/goalapa/cacamuca/foodDomain/query/domain/service/QueryFoodService.java
  src/main/java/com/goalapa/cacamuca/statDomain/command/application/dto/StatDTO.java
  src/main/java/com/goalapa/cacamuca/statDomain/command/application/service/SaveStatServiceImpl.java
  src/main/java/com/goalapa/cacamuca/statDomain/command/application/service/StatScheduler.java
  src/main/java/com/goalapa/cacamuca/statDomain/command/domain/aggregate/entity/Stat.java
  src/main/java/com/goalapa/cacamuca/statDomain/query/application/dto/QueryStatDTO.java
  src/main/resources/db/data/data.sql
  src/main/resources/mapper/GetStatMapper.xml
  src/main/resources/static/assets/img/Oreo-Two-Cookies.jpg
  src/main/resources/static/assets/img/chickchok.png
  src/main/resources/static/assets/img/chocoroll.jpg
  src/main/resources/static/assets/img/chorokmaesil.jpg
  src/main/resources/templates/main.html
Labels: ✨feature, 🎨design

#159 #47 [카테고리] 카테고리 수정
  src/main/java/com/goalapa/cacamuca/categoryDomain/command/application/controller/CategoryController.java
  src/main/java/com/goalapa/cacamuca/categoryDomain/command/application/service/AddCategoryService.java
  src/main/java/com/goalapa/cacamuca/categoryDomain/command/application/service/UpdateCategoryService.java
  src/main/java/com/goalapa/cacamuca/categoryDomain/command/domain/repository/CategoryRepository.java
  src/main/java/com/goalapa/cacamuca/categoryDomain/command/domain/service/CategoryService.java
Labels: ✨feature

#160 #88, #90 [식품]식품 등록, 삭제
  src/main/java/com/goalapa/cacamuca/categoryDomain/command/application/service/Service.java
  src/main/java/com/goalapa/cacamuca/foodDomain/command/application/controller/FoodController.java
  src/main/java/com/goalapa/cacamuca/foodDomain/command/application/service/FoodRegistService.java
  src/main/java/com/goalapa/cacamuca/foodDomain/command/application/service/SaveFoodFromRequestImpl.java
  src/main/java/com/goalapa/cacamuca/foodDomain/command/application/service/SaveFoodPicFromRequestImpl.java
  src/main/java/com/goalapa/cacamuca/foodDomain/command/domain/aggregate/entity/FoodEntity.java
  src/main/java/com/goalapa/cacamuca/foodDomain/command/domain/aggregate/entity/FoodPicEntity.java
  src/main/java/com/goalapa/cacamuca/foodDomain/command/domain/repository/FoodPicRepository.java
  src/main/java/com/goalapa/cacamuca/foodDomain/command/domain/repository/FoodRepository.java
  src/main/java/com/goalapa/cacamuca/foodDomain/query/application/controller/Controller.java
  src/main/java/com/goalapa/cacamuca/foodDomain/query/application/controller/QueryFoodController.java
  src/main/java/com/goalapa/cacamuca/foodDomain/query/application/service/QueryFoodService.java
  src/main/java/com/goalapa/cacamuca/foodDomain/query/domain/aggregate/dto/CheckFoodDTO.java
  src/main/java/com/goalapa/cacamuca/foodDomain/query/domain/aggregate/entity/Food.java
  src/main/java/com/goalapa/cacamuca/foodDomain/query/domain/entity/Entity.java
  src/main/java/com/goalapa/cacamuca/foodDomain/query/domain/repository/FoodRegistMapper.java
  src/main/java/com/goalapa/cacamuca/foodDomain/query/domain/repository/FoodRegistPicMapper.java
  src/main/java/com/goalapa/cacamuca/statDomain/command/application/service/StatScheduler.java
  src/main/resources/mapper/FoodRegistMapper.xml
  src/main/resources/templates/food-list.html
  src/main/resources/templates/food-regist.html
Labels: ✨feature

#152 Feature/member (#70, #124) [회원] 인가, 단위 테스트 검증
  src/main/java/com/goalapa/cacamuca/config/SecurityConfig.java
  src/main/java/com/goalapa/cacamuca/memberDomain/command/application/controller/CommandMemberController.java
  src/main/java/com/goalapa/cacamuca/memberDomain/command/application/service/CommandMemberServiceImpl.java
  src/main/java/com/goalapa/cacamuca/memberDomain/query/application/service/AuthenticationService.java
  src/main/resources/db/data/data.sql
  src/main/resources/templates/common/header.html
  src/test/java/com/goalapa/cacamuca/memberDomain/command/application/controller/CommandMemberControllerTest.java
  src/test/java/com/goalapa/cacamuca/memberDomain/command/application/service/CommandMemberServiceImplTest.java
  src/test/java/com/goalapa/cacamuca/memberDomain/query/application/controller/QueryMemberControllerTest.java
  src/test/java/com/goalapa/cacamuca/memberDomain/query/application/service/QueryCommandMemberServiceImplTest.java
Labels: ✨feature, 🎯test

#172 Feature/review (#161) 피드백 반영
  src/main/java/com/goalapa/cacamuca/reviewDomain/command/application/controller/ReviewController.java
  src/main/java/com/goalapa/cacamuca/reviewDomain/command/application/service/ReviewService.java
  src/main/java/com/goalapa/cacamuca/reviewDomain/command/domain/aggregate/entity/Review.java
  src/main/java/com/goalapa/cacamuca/reviewDomain/command/domain/repository/ReviewRepository.java
  src/main/java/com/goalapa/cacamuca/reviewDomain/query/application/controller/SelectReviewController.java
  src/main/java/com/goalapa/cacamuca/reviewDomain/query/application/dto/QueryReviewDTO.java
  src/main/java/com/goalapa/cacamuca/reviewDomain/query/application/service/SelectReviewService.java
  src/main/java/com/goalapa/cacamuca/reviewDomain/query/domain/repository/ReviewMapper.java
  src/main/resources/db/data/data.sql
  src/main/resources/mapper/ReviewMapper.xml
  src/main/resources/templates/common/aside.html
  src/main/resources/templates/review.html
  src/main/resources/templates/review/myReview.html
  src/main/resources/templates/review/report.html
  src/main/resources/templates/review/reviewDetail.html
  src/main/resources/templates/review/search.html
  src/main/resources/templates/review/selectReviews.html
  src/test/java/com/goalapa/cacamuca/reviewDomain/command/application/controller/Object/TestObjects.java
  src/test/java/com/goalapa/cacamuca/reviewDomain/command/application/controller/ReviewController.java
  src/test/java/com/goalapa/cacamuca/reviewDomain/query/domain/service/Service.java
  src/test/java/com/goalapa/cacamuca/reviewDomain/query/infrastructure/repository/Repository.java
  src/test/java/com/goalapa/cacamuca/reviewDomain/query/infrastructure/service/Service.java
Labels: 🎨design, ✅fix

#178 Feature/report create (#163) [신고] 피드백 반영
  src/main/java/com/goalapa/cacamuca/reportDomain/command/domain/aggregate/entity/BlackList.java
  src/main/java/com/goalapa/cacamuca/reportDomain/query/application/controller/ReportQueryController.java
  src/main/java/com/goalapa/cacamuca/reportDomain/query/application/dto/ReportQueryDTO.java
  src/main/resources/db/data/data.sql
  src/main/resources/mapper/ReportMapper.xml
  src/main/resources/templates/blacklistAdminPage.html
  src/main/resources/templates/common/header.html
  src/main/resources/templates/reportAdminPage.html
  src/main/resources/templates/review/reviewDetail.html
  src/test/java/com/goalapa/cacamuca/reportDomain/command/application/service/BlackListServiceTests.java
Labels: 🎨design, ✅fix

#183 Feature/appreview (#176)
  src/main/java/com/goalapa/cacamuca/statDomain/command/application/controller/StatController.java
  src/main/java/com/goalapa/cacamuca/statDomain/query/domain/respository/GetStatMapper.java
  src/main/java/com/goalapa/cacamuca/statDomain/query/domain/service/GetStatService.java
  src/main/resources/db/data/data.sql
  src/main/resources/mapper/GetStatMapper.xml
  src/main/resources/templates/appReview.html
  src/main/resources/templates/statDetail.html
Labels: ✨feature

#184 Feature/report create (#182) [신고] 버그 수정, 피드백 반영
  src/main/java/com/goalapa/cacamuca/reportDomain/command/application/controller/ReportController.java
  src/main/java/com/goalapa/cacamuca/reportDomain/command/application/service/ReportServiceImpl.java
  src/main/resources/db/data/data.sql
  src/main/resources/static/css/fonts.css
  src/main/resources/templates/blacklistAdminPage.html
  src/main/resources/templates/reportAdminPage.html
Labels: 🐞bugfix, 🎨design

#201 feat : (#200) 정렬 순서 변경 및 사진 미업로드 저장 기능 추가
  src/main/java/com/goalapa/cacamuca/foodDomain/command/domain/repository/FoodRepository.java
  src/main/java/com/goalapa/cacamuca/reviewDomain/command/application/controller/ReviewController.java
  src/main/java/com/goalapa/cacamuca/reviewDomain/command/application/dto/ReviewDTO.java
  src/main/java/com/goalapa/cacamuca/reviewDomain/command/application/service/ReviewService.java
  src/main/java/com/goalapa/cacamuca/reviewDomain/command/infrastructure/service/ReviewValidationServiceImpl.java
  src/main/java/com/goalapa/cacamuca/reviewDomain/query/application/controller/SelectReviewController.java
  src/main/resources/db/data/data.sql
  src/main/resources/templates/review.html
  src/main/resources/templates/review/selectReviews.html
  src/test/java/com/goalapa/cacamuca/reviewDomain/command/application/controller/Object/TestObjects.java
  src/test/java/com/goalapa/cacamuca/reviewDomain/command/application/controller/ReviewController.java
Labels: 🐞bugfix, ✨feature

#203 Feature/report create [신고] 테스트 버그 수정
  src/main/java/com/goalapa/cacamuca/categoryDomain/command/application/controller/CategoryController.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/db/data/ddl.sql
  src/main/resources/mapper/FoodRegistMapper.xml
  src/test/java/com/goalapa/cacamuca/memberDomain/query/application/controller/QueryMemberControllerTest.java
  src/test/java/com/goalapa/cacamuca/memberDomain/query/application/service/WithMockUserTests.java
  src/test/java/com/goalapa/cacamuca/reportDomain/command/application/service/ReportServiceTests.java
Labels: 🐞bugfix, 🎯test

#206 Feature/member (#191,#205) 회원목록 성별 조회, 배포(member 테이블 컬럼에 코멘트)
  src/main/java/com/goalapa/cacamuca/memberDomain/command/domain/aggregate/entity/Member.java
  src/main/java/com/goalapa/cacamuca/memberDomain/command/domain/aggregate/vo/BirthDay.java
  src/main/java/com/goalapa/cacamuca/memberDomain/command/domain/aggregate/vo/Password.java
  src/main/java/com/goalapa/cacamuca/memberDomain/query/application/service/AuthenticationService.java
  src/main/java/com/goalapa/cacamuca/reviewDomain/query/application/controller/SelectReviewController.java
  src/main/resources/mapper/MemberMapper.xml
  src/main/resources/templates/adminList.html
Labels: 🐞bugfix
